### ISSUE TITLE
Deployment: Setup Github actions and Jest

### ISSUE THREAD

**Issue by dinarabs** [itzMaffi/CW-thesis-project#7]
- setup Jest for vite react
- setup Github actions for PRs.

**Comment by itzMaffi** [comment]
If I remember correctly from the lecture, there were some problems with mongodb atlas not having a fixed ip available in the free tier (or was it fly.io?). Anyway, something couldn't be set up correctly to achieve a decent level of security (something about allowin all ips). So I was thinking if flyio can run docker, we could host the dbs in flyio as well?

**Comment by dayt47** [comment]
i think this should work with fly.io (i mean the db with docker) but i don't know how mich tinkering is needed. on fly.io you can get a dedicated ipv4 address for 2$ / month: 

**citation:**
"Anycast IP addresses

Each application receives a [shared IPv4 address](https://fly.io/docs/reference/services/#shared-ipv4) and unlimited [Anycast IPv6](https://fly.io/docs/reference/services/#ipv6) addresses for global load balancing.

Dedicated IPv4 addresses are $2/mo."

**Comment by dinarabs** [comment]
Just saw this convo, FYI that screenshots were from yday's research i was doing, so you can ignore them :) 

i think we decided to deploy both client/server to `fly.io` per @dayt47 research and experiment and regarding mongodb atlas i haven't done research tbh
